### ISSUE TITLE
Ultron error?

### ISSUE THREAD

**Issue by psthree** [unshiftio/ultron#9]
When I run browser-sync start --server --directory --files "**/*" 
it works when I switch to another page or update my code i get this error

 Watching files...
/usr/local/lib/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/ultron/index.js:80
      if (this.ee._events.hasOwnProperty(event)) {
                          ^

TypeError: this.ee._events.hasOwnProperty is not a function
    at Ultron.remove (/usr/local/lib/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/ultron/index.js:80:27)
    at Ultron.destroy (/usr/local/lib/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/ultron/index.js:116:8)
    at WebSocket.cleanupWebsocketResources (/usr/local/lib/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/lib/WebSocket.js:851:36)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:934:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

Not sure if its something I am doing or that something needs to be reconfigerd?
thank you
psthree@aol.com

**Comment by lpinca** [comment]
Yes it seems an `ultron` issue, but from the stack trace I can say that the `ultron` version is 1.0.1. `1.0.2` is not affected by that issue.
Are you using the latest version of `browser-sync`?

**Comment by psthree** [comment]
Sorry have not been able to post sooner
I updated to the new version and the problem went away :-)

 

 

 

-----Original Message-----

**Comment by lpinca** [comment]
Thanks, closing then.

**Comment by psthree** [comment]
Thank you!
 

 

 

-----Original Message-----
